"""empty message

Revision ID: 2d3bfa47b8d2
Revises: 5f5b0bf99cf7
Create Date: 2023-01-05 09:54:50.414142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3bfa47b8d2'
down_revision = '5f5b0bf99cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('change_password', sa.Boolean(), nullable=False, server_default='FALSE'))
    # ### end Alembic commands ###

    # Change password for all users
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    session.execute("UPDATE users SET change_password = true")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'change_password')
    # ### end Alembic commands ###
