FROM nginx:1.23

RUN rm /etc/nginx/conf.d/default.conf
COPY ./default.conf /etc/nginx/conf.d

#COPY ./nginx/default-ssl.conf /etc/nginx/conf.d/default.conf
#COPY ./nginx/configtracker.crt /tmp
#COPY ./nginx/configtracker.key /tmp
